[project]
name = "python-flow"
version = "0.0.1"

requires-python = ">=3.8"

[project.optional-dependencies]
test = ["pytest==7.2.0", "pytest-freezegun==0.4.2", "pytest-asyncio==0.23.2"]
build = ["build==1.0.3"]
graphs = ["graphviz==0.20.3"]
